### ISSUE TITLE
[Feat] 언제나 가까이 ~ 하단배너 UI 디테일 구현

### ISSUE THREAD

**Issue by sozohoy** [NOW-SOPT-APP7-GS-HOMETOWN/GsHometown-iOS#8]
## 💡 Issue

- 위치만 잡아놨던 UI를 디테일하게 구현합니다.

## 📝 Todo
- [x] 언제나 가까이 & 더프레시 섹션 디테일 구현
- [x] 나만의 냉장고 ~ 와인 25+ 섹션 디테일 구현
- [x] 많이 찾는 서비스 배경 추가
- [x] 하단 배너 및 이번주 할인 행사 섹션 위치 조정
